In [7]:
import glob
import numpy as np
import os

import tensorflow as tf

In [ ]:
#!pip install --upgrade tensorflow

In [3]:
# must be >=2.6.2
tf.__version__

'2.6.2'

In [18]:
header = {"frame":0, "id":1, "x":2, "y":3, "w":4, "h":5, "x1":6, "x2":7, "conf":9}
threshold = 0.9

In [33]:


videos = glob.glob("data/test/*/det/det.txt")

for video in videos:
    print("Evaluating on file: {}".format(file))
    data_video = np.loadtxt(file, delimiter=",")
    frames = np.unique(data[:,header["frame"]])
    # put an id on all objects in the first frame
    first_frame = min(frames)
    data_first_frame = data_video[data_video[:,header["frame"]]==first_frame,:]
    largest_id = len(data_old_frame)
    old_objs = # all objs from first frame in a tensor
    old_id_map = list(range(1,largest_id+1)) # map from position in tensor above to id of object
    data_first_frame[:,header["id"]] = old_id_map
    
    # iterate through frames, on each next frame find the best match from
    # the objects of the previous match and remember the matching score. 
    # The matching score must be larger than a certain threshold. Not 
    # more than 1 objects in the next frame can be matched to one object in the
    # previous frame, so recursively go through all unmatched objects until they
    # are all matched. If no match is found for an object, assigned a new id 
    # being largest_id + 1 
    for frame in frames:
        data_new_frame = data_video[data_video[:,header["frame"]]==frame,:]
        new_objs = # all objs from this new frame in a tensor
        new_id_map = [] # map from position in tensor above to id of object
        for r,det in enumerate(data_new_frame):
            new_obj = # a tensor of all same pictures with same dim as old_obj
            similarities = compute_similarity(new_obj, old_obj)
            i = np.argmax(similarities)
            score = similarities[i]
            if score > thresh:
                new_id_map += [old_id_map[i]]
            else:
                largest_id += 1
                new_id_map += [largest_id]
        
        data_new_frame[:,header["id"]] = new_id_map
        
        #update old variables
        old_objs = new_objs
        old_id_map = new_id_map
        

Evaluating on file: data/test/MOT16-01/det/det.txt
[[ 1.0000e+00  1.0000e+00  7.7268e+02  4.5543e+02  4.1871e+01  1.2761e+02
   2.1262e+00 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  2.0000e+00  7.1779e+02  4.5129e+02  4.4948e+01  1.3684e+02
   1.7969e+00 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  3.0000e+00  2.3074e+02  4.6507e+02  2.1974e+01  6.7922e+01
   1.6718e+00 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  4.0000e+00  1.0017e+03  4.5586e+02  6.3980e+01  1.9394e+02
   6.3705e-01 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  5.0000e+00  7.0264e+02  3.7421e+02  7.3643e+01  2.2293e+02
  -1.0042e-01 -1.0000e+00 -1.0000e+00 -1.0000e+00]]


In [24]:
data = np.loadtxt(files[0],delimiter=",")
data

array([[ 1.0000e+00, -1.0000e+00,  7.7268e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 1.0000e+00, -1.0000e+00,  7.1779e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 1.0000e+00, -1.0000e+00,  2.3074e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       ...,
       [ 4.5000e+02, -1.0000e+00,  1.7248e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 4.5000e+02, -1.0000e+00,  2.8900e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 4.5000e+02, -1.0000e+00,  1.6055e+03, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00]])

In [27]:
data_a = data[0:1,0:1]

In [42]:
a = set()

In [45]:
len(a)==0

True

In [23]:
frames = np.unique(data[:,header["frame"]])


array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

# Testing my model imports

In [1]:
import tensorflow as tf

from siamese_model_image_location import get_siamese_model
from train_val_gen_image_location import triplet_gen

In [2]:
target_shape = (200,200)
batch_size = 64

In [ ]:
# build the train dataset
train_dataset = tf.data.Dataset.from_generator(triplet_gen("train", batch_size, target_shape), ((tf.float32,tf.float32),(tf.float32,tf.float32),(tf.float32,tf.float32)), ((target_shape + (3,),(4,)),(target_shape + (3,),(4,)),(target_shape + (3,),(4,))))
train_dataset = train_dataset.shuffle(buffer_size=2^14)
train_dataset = train_dataset.batch(batch_size, drop_remainder=True) #TODO: should set to False?
train_dataset = train_dataset.prefetch(8)

# build the test dataset
val_dataset = tf.data.Dataset.from_generator(triplet_gen("val", batch_size, target_shape), ((tf.float32,tf.float32),(tf.float32,tf.float32),(tf.float32,tf.float32)), ((target_shape + (3,),(4,)),(target_shape + (3,),(4,)),(target_shape + (3,),(4,))))
val_dataset = val_dataset.shuffle(buffer_size=2^14)
val_dataset = val_dataset.batch(batch_size, drop_remainder=True) #TODO: should set to False?
val_dataset = val_dataset.prefetch(8)

In [ ]:
# build (and load if load_model_path is not None) the siamese_model
siamese_model = get_siamese_model(target_shape, load_model_path = None)

In [ ]:
# train the model
siamese_model.fit(train_dataset, epochs=10, validation_data=val_dataset, batch_size = batch_size)

Epoch 1/10
    166/Unknown - 1503s 9s/step - loss: 0.2040

In [5]:
# save the model
siamese_model.siamese_network.save("models/siamese_network_2/model_0")

INFO:tensorflow:Assets written to: models/siamese_network_2/model_0/assets


/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)


In [7]:
# load the trained model
siamese_model = get_siamese_model(target_shape, load_model_path = "models/siamese_network_2/model_0")

In [9]:
# evaluate the model
for xi in train_dataset:
    print(siamese_model(xi))
    break
# get the embedding, we really want to save the embedding rather than the whole model.. and then run the test examples on the embedding (
# the test examples are not triplets but rather just an image and a location. 

(<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([0.0027987 , 0.43512282, 0.11399516, 0.21958008, 0.6719003 ,
       0.0356839 , 0.32577905, 0.11854939, 0.05120662, 0.06752269,
       0.5898831 , 0.72008634, 0.31534147, 0.39584357, 0.9709426 ,
       0.2655549 , 0.7045237 , 0.28984952, 1.5087411 , 0.16760036,
       1.4004412 , 0.12871963, 0.70179796, 0.7404676 , 0.19323258,
       0.38675585, 0.64490104, 0.48554426, 0.58698106, 0.91979396,
       0.9395615 , 0.03203043, 0.06709439, 0.27407357, 0.07012771,
       0.1825794 , 1.288773  , 0.06101909, 0.06845597, 0.31462198,
       0.9549992 , 0.20126264, 0.11504369, 0.72868454, 0.25455585,
       0.25545657, 0.08357295, 0.16108814, 0.60716534, 0.24333848,
       1.2144446 , 1.0054178 , 0.11314649, 0.93689275, 1.071589  ,
       0.00949483, 0.79136837, 0.70707566, 0.8960537 , 0.45198822,
       1.2047791 , 1.4274633 , 0.27333677, 1.8147753 ], dtype=float32)>, <tf.Tensor: shape=(64,), dtype=float32, numpy=
array([2.556416  , 2.4612484