In [7]:
import glob
import numpy as np
import os

import tensorflow as tf

In [ ]:
#!pip install --upgrade tensorflow

In [3]:
# must be >=2.6.2
tf.__version__

'2.6.2'

In [18]:
header = {"frame":0, "id":1, "x":2, "y":3, "w":4, "h":5, "x1":6, "x2":7, "conf":9}
threshold = 0.9

In [33]:


videos = glob.glob("data/test/*/det/det.txt")

for video in videos:
    print("Evaluating on file: {}".format(file))
    data_video = np.loadtxt(file, delimiter=",")
    frames = np.unique(data[:,header["frame"]])
    # put an id on all objects in the first frame
    first_frame = min(frames)
    data_first_frame = data_video[data_video[:,header["frame"]]==first_frame,:]
    largest_id = len(data_old_frame)
    old_objs = # all objs from first frame in a tensor
    old_id_map = list(range(1,largest_id+1)) # map from position in tensor above to id of object
    data_first_frame[:,header["id"]] = old_id_map
    
    # iterate through frames, on each next frame find the best match from
    # the objects of the previous match and remember the matching score. 
    # The matching score must be larger than a certain threshold. Not 
    # more than 1 objects in the next frame can be matched to one object in the
    # previous frame, so recursively go through all unmatched objects until they
    # are all matched. If no match is found for an object, assigned a new id 
    # being largest_id + 1 
    for frame in frames:
        data_new_frame = data_video[data_video[:,header["frame"]]==frame,:]
        new_objs = # all objs from this new frame in a tensor
        new_id_map = [] # map from position in tensor above to id of object
        for r,det in enumerate(data_new_frame):
            new_obj = # a tensor of all same pictures with same dim as old_obj
            similarities = compute_similarity(new_obj, old_obj)
            i = np.argmax(similarities)
            score = similarities[i]
            if score > thresh:
                new_id_map += [old_id_map[i]]
            else:
                largest_id += 1
                new_id_map += [largest_id]
        
        data_new_frame[:,header["id"]] = new_id_map
        
        #update old variables
        old_objs = new_objs
        old_id_map = new_id_map
        

Evaluating on file: data/test/MOT16-01/det/det.txt
[[ 1.0000e+00  1.0000e+00  7.7268e+02  4.5543e+02  4.1871e+01  1.2761e+02
   2.1262e+00 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  2.0000e+00  7.1779e+02  4.5129e+02  4.4948e+01  1.3684e+02
   1.7969e+00 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  3.0000e+00  2.3074e+02  4.6507e+02  2.1974e+01  6.7922e+01
   1.6718e+00 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  4.0000e+00  1.0017e+03  4.5586e+02  6.3980e+01  1.9394e+02
   6.3705e-01 -1.0000e+00 -1.0000e+00 -1.0000e+00]
 [ 1.0000e+00  5.0000e+00  7.0264e+02  3.7421e+02  7.3643e+01  2.2293e+02
  -1.0042e-01 -1.0000e+00 -1.0000e+00 -1.0000e+00]]


In [24]:
data = np.loadtxt(files[0],delimiter=",")
data

array([[ 1.0000e+00, -1.0000e+00,  7.7268e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 1.0000e+00, -1.0000e+00,  7.1779e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 1.0000e+00, -1.0000e+00,  2.3074e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       ...,
       [ 4.5000e+02, -1.0000e+00,  1.7248e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 4.5000e+02, -1.0000e+00,  2.8900e+02, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00],
       [ 4.5000e+02, -1.0000e+00,  1.6055e+03, ..., -1.0000e+00,
        -1.0000e+00, -1.0000e+00]])

In [27]:
data_a = data[0:1,0:1]

In [42]:
a = set()

In [45]:
len(a)==0

True

In [23]:
frames = np.unique(data[:,header["frame"]])


array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

# Testing my model imports

In [1]:
import tensorflow as tf

from siamese_model_image_location import get_siamese_model
from train_val_gen_image_location import triplet_gen

In [2]:
target_shape = (200,200)
batch_size = 64

In [3]:
# build the train dataset
train_dataset = tf.data.Dataset.from_generator(triplet_gen("train", batch_size, target_shape), ((tf.float32,tf.float32),(tf.float32,tf.float32),(tf.float32,tf.float32)), ((target_shape + (3,),(4,)),(target_shape + (3,),(4,)),(target_shape + (3,),(4,))))
train_dataset = train_dataset.shuffle(buffer_size=2^14)
train_dataset = train_dataset.batch(batch_size, drop_remainder=True) #TODO: should set to False?
train_dataset = train_dataset.prefetch(8)

# build the test dataset
val_dataset = tf.data.Dataset.from_generator(triplet_gen("val", batch_size, target_shape), ((tf.float32,tf.float32),(tf.float32,tf.float32),(tf.float32,tf.float32)), ((target_shape + (3,),(4,)),(target_shape + (3,),(4,)),(target_shape + (3,),(4,))))
val_dataset = val_dataset.shuffle(buffer_size=2^14)
val_dataset = val_dataset.batch(batch_size, drop_remainder=True) #TODO: should set to False?
val_dataset = val_dataset.prefetch(8)

In [4]:
# build (and load if load_model_path is not None) the siamese_model
siamese_model = get_siamese_model(target_shape, load_model_path = None)

In [5]:
# train the model
siamese_model.fit(train_dataset, epochs=10, validation_data=val_dataset, batch_size = batch_size)

Epoch 1/10
      3/Unknown - 42s 10s/step - loss: 0.3677

KeyboardInterrupt: 

In [5]:
# save the model
siamese_model.siamese_network.save("models/siamese_network_2/model_0")

INFO:tensorflow:Assets written to: models/siamese_network_2/model_0/assets


/home/ec2-user/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/keras/utils/generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)


In [7]:
# load the trained model
siamese_model = get_siamese_model(target_shape, load_model_path = "models/siamese_network_2/model_0")

In [6]:
# evaluate the model
for xi in train_dataset:
    print(siamese_model(xi))
    break
# get the embedding, we really want to save the embedding rather than the whole model.. and then run the test examples on the embedding (
# the test examples are not triplets but rather just an image and a location. 

(<tf.Tensor: shape=(64,), dtype=float32, numpy=
array([0.14314848, 0.03569299, 0.08460955, 0.40625623, 0.44383675,
       0.07046042, 0.3818026 , 0.03915355, 0.25170058, 0.02380638,
       0.71722186, 0.03509968, 0.12621234, 0.42653406, 0.16551697,
       0.05132472, 0.06445332, 0.37494037, 0.07118455, 0.11165597,
       0.07152015, 0.07872263, 0.10603108, 0.05835205, 0.10887954,
       0.06431368, 0.35207164, 0.15309969, 0.47329527, 0.1544779 ,
       0.10742479, 0.07486513, 0.01661921, 0.04822332, 0.5183967 ,
       0.0760931 , 0.17659846, 0.21260379, 0.09629159, 0.05572436,
       0.02591301, 0.1194004 , 0.58771414, 0.17668265, 0.36010253,
       0.34608102, 0.05447887, 0.04927808, 0.5391364 , 0.3907263 ,
       0.05363579, 0.14205173, 0.05807609, 0.01742748, 0.79502606,
       0.02510771, 0.28954464, 0.12343122, 0.1652107 , 0.67124367,
       0.387415  , 0.12090991, 0.00789902, 0.40083677], dtype=float32)>, <tf.Tensor: shape=(64,), dtype=float32, numpy=
array([0.14624867, 0.2272467